artículo nube de palabras en R
OpenScienceLabs/opensciencelabs.github.io-archive pull request #19
Opened 2022-03-02 00:32 UTC by EverVino

@xmnlab @petrizzo @eunrod16 Aqui un nuevo artículo para su revisión. Use un jupyterlab para crearlo y adjunto los archivos necesarios para su ejecución dinámica. Aún no esta integrado con NIKOLA (en los siguientes días me encargo de ello) pero su contenido raw está listo.

2022-03-02 21:36 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +   "tags": "R, RStudio, nube de palabras, wordcloud, mineria de texto",
@EverVino poderías poner todo en minúsculas?

```suggestion
   "tags": "r, rstudio, nube de palabras, wordcloud, mineria de texto",
```

si tenemos tags escritas en un lugar con minuscula y en otro lugar con mayúscula, va a saltar algún error:

```
[2022-03-02 21:22:10] ERROR: Nikola: You have classifications that are too similar: tag "r" and tag "R" both result in output path categories/r/index.html for language es.
[2022-03-02 21:22:10] ERROR: Nikola: Tag "r" is used in: pages/blog/0032-visualizacionR/visualizacionR.md, pages/blog/0045-rOpenSci/rOpenSci.md, pages/blog/0055-Rstudio/Rstudio.md, pages/blog/0057-r-ggplot-bo/ArticuloGgplotenR.md, pages/blog/0059-r-maps-viz/GraficaMapasR.md
[2022-03-02 21:22:10] ERROR: Nikola: Tag "R" is used in: pages/blog/0061-r-nube-palabras/nubeR.ipynb
```

si normalizamos entre nosotros todo en minúsculas, evitamos tener estos tipos de problemas :)

2022-03-02 21:36 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +   "category": "open science",
```suggestion
   "category": "r",
```

2022-03-03 19:30 UTC, xmnlab requested changes
@EverVino he hecho una revisión inicial y parcial .. ya he agregado unos comentarios.
en el texto markdown , sería bueno si todas las variables y tipos de variables estuvieran entre ``` ` ```. también puedes aplicar esta reglar si estás hablando de una librería dentro de código. por ejemplo:  "para tal, importe la librería `tidyverse`"

para nombres de librerías, programas, etc cuando no tiene que ver con código, poner en negritas: `**tidyverse** es una librería bastante buena. también puedes usarla en **Windows**`

me avises cuando tengas esto aplicado, y sigo con la revisión.

he visto el resultado en https://app.reviewnb.com/OpenScienceLabs/opensciencelabs.github.io/pull/19/

y se ve genial. muchas gracias por trabajar en este artículo!

me avisas si necesitas cualquier ayuda

2022-03-03 19:30 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +    "**Autor:** [Ever Vino](https://opensciencelabs.github.io/articles/authors/ever-vino.html)\n",
```suggestion
```

No se necesitas más poner el autor aquí, nikola lo hará automaticamente con los metadatos

2022-03-03 19:30 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +    "En este tutorial usaremos el artículo de [inteligencia artificial](https://es.wikipedia.org/wiki/Inteligencia_artificial) de Wikipedia, para construir nuestra nube de palabras usando las bibliot
```suggestion
    "En este tutorial, usaremos el artículo de [inteligencia artificial](https://es.wikipedia.org/wiki/Inteligencia_artificial) de Wikipedia para construir nuestra nube de palabras usando las bibliotecas `tm` y `wordcloud`.\n"
```

2022-03-03 19:30 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +    "Nuestra fuente de datos es el archivo `texto.txt` que esta dentro de nuestra carpeta de trabajo. Para saber la carpeta de trabajo puede ejecutar `getwd()`. Para cambiar la carpeta de trabajo use
en lugar de tener el archivo dentro del repositorio, mejor si subes el archivo a un gist e de allá vas a tener un link para `raw`. Así, cualquiera podrá reproducir facilmente tu notebook.

en tu notebook .. puedes usar comandos para bajar el archivo, por ejemplo:

`wget https://gist.githubusercontent.com/xmnlab/6b18a00e83e568ba3eb5a84cbc08d66d/raw/d71df8602f8ecc82b95ea0ed712d38c2c9e28c10/argo-workflow.yaml -o /tmp/argo-workflow.yaml`

2022-03-03 19:30 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +    "Luego de importar el texto vamos a convertirlo en un objeto tipo Source, esto facilitará la minería del texto y su posterior modificación."
```suggestion
    "Luego de importar el texto, vamos a convertirlo en un objeto tipo `Source`, esto facilitará la minería del texto y su posterior modificación."
```

2022-03-03 19:30 UTC, xmnlab commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +    "* `VCorpus (x, readerControl(y))`: Donde x es un objeto del tipo Source, se recomienda que sea un objeto del tipo VectorSource. Para `readerControl(y)` `y` es una lista de parámetros para leer `
```suggestion
    "* `VCorpus (x, readerControl(y))`: Donde `x` es un objeto del tipo Source, se recomienda que sea un objeto del tipo `VectorSource`. Para `readerControl(y)` `y` es una lista de parámetros para leer `x`.\n",
```

2022-03-05 21:55 UTC, EverVino commented
Gracias por la revisión @xmnlab Ya hice la correcciones

2022-03-14 23:54 UTC, esloch commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +   "slug": "nube-palabras-r",
Para el slug ahora vamos a seguir un patrón; el slug será lo mismo del title, podremos usar este [enlace](https://slugify.online/) para generar el slug.
Queda algo como:
 **crea-una-nube-de-palabras-en-r-partir-de-un-documento-de-texto**

2022-03-14 23:54 UTC, esloch commented on pages/blog/0061-r-nube-palabras/nubeR.ipynb
> +    "![Convertir un texto a Nube de palabras ](header.png)\n",
Todos los imágenes a partir de ahora se guardarán  el directorio: **/images/blog**, asi que el patron para que pueda ser asequible tendrá ese formato: **![Convertir un texto a Nube de palabras ](../../../images/blog/header.png)***
Recuerda siempre poner los 3 niveles superiores ***(../../../)*** antes de del directorio */images*.

2022-03-15 00:02 UTC, esloch commented
Gracias @EverVino!

2022-03-15 20:08 UTC, EverVino commented
Gracias @esloch, ya hice las modificaciones solicitadas.

2022-03-16 23:01 UTC, merged

2022-03-16 23:01 UTC, xmnlab commented
thanks @EverVino !