Nuevo artículo tidyr
OpenScienceLabs/opensciencelabs.github.io-archive pull request #57
Opened 2022-07-27 03:04 UTC by EverVino

Nuevo artículo para revisión Reorganiza tu tabla con tidyr en R.
@xmnlab

2022-07-27 14:07 UTC, luabida reviewed
Looks great! Thank you

@EverVino I see your branch is in an older version. Could you do a rebase to get the updates from upstream/main?
OBS: the last commit in your branch is from Jun 15, the version is outdated. Ty

2022-07-27 17:43 UTC, luabida commented on pages/blog/filtrar-datos-r/art-filtrar-datos.md
> +Por comodidad usamos la biblioteca `pacman` como gestor de paquetes.
Change `gestor` to `gestar`

2022-07-28 00:22 UTC, EverVino commented
Done 

> Looks great! Thank you
> 
> @EverVino I see your branch is in an older version. Could you do a rebase to get the updates from upstream/main? OBS: the last commit in your branch is from Jun 15, the version is outdated. Ty

It has been done. Thanks for the review.

2022-07-29 14:56 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Importamos los el archivo `.csv` a la variable `datos_turistas`.
quitar "los"

2022-07-29 14:56 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Recuerde, que tambien puede instalar y abrir las bibliotecas de manera tradicional, por ejemplo con: `install.packages("tidyr")`, luego abrir la misma biblioteca con `library(tidyr)`.
cambiar "tambien" por "también"

2022-07-29 14:56 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Nuestra tabla tiene varias columnas correspondientes al acumulativo por mes. Si queremos graficar estos datos con `ggplot` estos datos no nos van a ser de mucha utilidad. Por ello vamos a usar `gathe
cambiar "sóla" por "sola"

2022-07-29 14:56 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- **`...`** : Nombres o seleccion de columnas a agruparse, puede usar los nombres de las columnas con la función concatenate `c()`. Ejemplo `c(nombre_col1, nombre_col2...)`  ó hacer la selección del
cambiar "seleccion" por la palabra "selección"
cambiar "concatenate" por la palabra "concatenar"

2022-07-29 14:56 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- **`into`** : Nombres de la nuevas columnas que van a crearse a partir de `col`. Puede usar para nombrar a las columnas la función concatenate `c()`.
cambiar "concatenate" por la palabra "concatenar"

2022-07-29 14:56 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- **`... `** : Nombres de la nuevas columnas que van a juntarse en `col`. Puede usar para nombrar las columnas la función concatenate `c()`.
cambiar "concatenate" por la palabra "concatenar"

2022-07-29 15:16 UTC, xmnlab commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +En este artículo modificaremos la forma de nuestra tabla, combinando varias columnas en una sola o viceversa, usando la biblioteca `tidyr` con sus funciones `gather()`, `spread()`, `separate()`, y `u
```suggestion
En este artículo, modificaremos la forma de nuestra tabla, combinando varias columnas en una sola o viceversa, usando la biblioteca `tidyr` con sus funciones `gather()`, `spread()`, `separate()`, y `unite()` con ejemplos.
```

2022-07-30 02:35 UTC, EverVino commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Importamos los el archivo `.csv` a la variable `datos_turistas`.
Hecho.

2022-07-30 02:35 UTC, EverVino commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Recuerde, que tambien puede instalar y abrir las bibliotecas de manera tradicional, por ejemplo con: `install.packages("tidyr")`, luego abrir la misma biblioteca con `library(tidyr)`.
Hecho

2022-07-30 02:36 UTC, EverVino commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Nuestra tabla tiene varias columnas correspondientes al acumulativo por mes. Si queremos graficar estos datos con `ggplot` estos datos no nos van a ser de mucha utilidad. Por ello vamos a usar `gathe
Hecho.

2022-07-30 02:36 UTC, EverVino commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- **`...`** : Nombres o seleccion de columnas a agruparse, puede usar los nombres de las columnas con la función concatenate `c()`. Ejemplo `c(nombre_col1, nombre_col2...)`  ó hacer la selección del
Hecho.

2022-07-30 02:36 UTC, EverVino commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- **`into`** : Nombres de la nuevas columnas que van a crearse a partir de `col`. Puede usar para nombrar a las columnas la función concatenate `c()`.
Hecho

2022-07-30 02:36 UTC, EverVino commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- **`... `** : Nombres de la nuevas columnas que van a juntarse en `col`. Puede usar para nombrar las columnas la función concatenate `c()`.
Hecho, gracias por la revisión.

2022-08-03 02:14 UTC, Gretzel requested changes

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +# También podemos utilizar la columna `Fecha` para tranformar a trimestres, con el argumento `format=%d/%m/%y`
```suggestion
# También podemos utilizar la columna `Fecha` para transformar a trimestres, con el argumento `format=%d/%m/%y`
```

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Ahora podemos usamos `spread()`, para expandir los datos de la columna trimestre en columnas independientes.
```suggestion
Ahora podemos usar `spread()`, para expandir los datos de la columna trimestre en columnas independientes.
```

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Ahora observamos que nuestros se han esparcido, este formato es útil para visualización de datos en otros frameworks.
```suggestion
Ahora observamos que nuestros datos se han esparcido, este formato es útil para visualización de datos en otros frameworks.
```

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Función que es usada para esparcir los datos de una como nombres de columnas.
```suggestion
Función que es usada para esparcir los datos de una columna como nombres de columnas.
```

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +Aprovechemos esta estos datos para graficar los top paises que han visitado Bolivia en el primer trimestre trimestre del 2019.
```suggestion
Aprovechemos estos datos para graficar los top países que han visitado Bolivia en el primer trimestre  del 2019.
```

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +- [Documentacion de R](https://www.rdocumentation.org)
```suggestion
- [Instituto de Estadística de Bolivia (INE)](https://www.ine.gob.bo/)

- [Documentación de R](https://www.rdocumentation.org)
```

2022-08-03 02:14 UTC, Gretzel commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +La función `gather()` puede agrupar muchas los nombres de las columnas en una sola, así como se muestra en la siguiente animación
```suggestion
La función `gather()` puede agrupar muchas los nombres de las columnas en una sola, así como se muestra en la siguiente animación.
```

2022-08-03 02:19 UTC, xmnlab commented on pages/blog/reorganiza-tus-tablas-con-tidyr/art-reorganiza-datos.md
> +La función `gather()` puede agrupar muchas los nombres de las columnas en una sola, así como se muestra en la siguiente animación
no entendí bien `puede agrupar muchas los nombres de las columnas`. se podría quitar "muchas"?

2022-08-03 17:12 UTC, xmnlab commented
@Gretzel, @EverVino ya ha aplicado tus sugerencias. poderías confirmar si está todo ok? si sí, podrías aprobar este PR?

2022-08-06 00:21 UTC, xmnlab commented
thanks for working on that @EverVino 
and thanks @Gretzel for the review

2022-08-06 00:22 UTC, xmnlab approved these changes

2022-08-06 00:22 UTC, merged