Review of articles 0032 and 0055
OpenScienceLabs/opensciencelabs.github.io-archive pull request #66
Opened 2022-08-02 02:49 UTC by Anavelyz

Revisión de artículos: Primeros pasos con RStudio y Herramientas de visualización en R.

Sugerencias de palabras para el artículo 0032: R, visualización, lattice, ggplot2, tidyverse, ggmap, plotly, shiny, paquetes...

Sugerencias de palabras para el artículo 0055: R, RStudio, IDE, RStudio Desktop, RStudio Server, Interfaz, paquetes...

P. D.: Tengo una duda, algunos enlaces aparecen de la forma \[texto]\(enlace). ¿Qué diferencia hay con respecto a los enlaces en formato [texto](enlace)?... (la diferencia es la aparición de `\`)

2022-08-02 17:14 UTC, EverVino commented
> Revisión de artículos: Primeros pasos con RStudio y Herramientas de visualización en R.
> 
> Sugerencias de palabras para el artículo 0032: R, visualización, lattice, ggplot2, tidyverse, ggmap, plotly, shiny, paquetes...
> 
> Sugerencias de palabras para el artículo 0055: R, RStudio, IDE, RStudio Desktop, RStudio Server, Interfaz, paquetes...
> 
> P. D.: Tengo una duda, algunos enlaces aparecen de la forma [texto](enlace). ¿Qué diferencia hay con respecto a los enlaces en formato `[texto](enlace)`?... (la diferencia es la aparición de `\`)
> 
> @EverVino

hola la diferencia es que "\" es un simbolo de escape, es decir cuando este simbolo, se encuentra delante de un commando lo anula:
Sin usar \
[google](www.google.com)
Usando \
\[google](www.google.com)

2022-08-02 17:39 UTC, EverVino requested changes
Gracias por revisar, hay algunas sugerencias hechas como comentarios.

2022-08-02 17:39 UTC, EverVino commented on pages/blog/0032-visualizacionR/visualizacionR.md
> +El paquete fue escrito por \[Deepayan Sarkar\](https://www.isid.ac.in/~deepayan/) con el
Borrar los los backslash "\\"

2022-08-02 17:39 UTC, EverVino commented on pages/blog/0032-visualizacionR/visualizacionR.md
> +información en (enlace a documentación o sitio web de ggmap).
modificar y agregar este link de la pagína de ggmap https://www.rdocumentation.org/packages/ggmap/versions/3.0.0

2022-08-02 17:50 UTC, EverVino commented
> Revisión de artículos: Primeros pasos con RStudio y Herramientas de visualización en R.
> 
> Sugerencias de palabras para el artículo 0032: R, visualización, lattice, ggplot2, tidyverse, ggmap, plotly, shiny, paquetes...
> 
> Sugerencias de palabras para el artículo 0055: R, RStudio, IDE, RStudio Desktop, RStudio Server, Interfaz, paquetes...
> 
> P. D.: Tengo una duda, algunos enlaces aparecen de la forma [texto](enlace). ¿Qué diferencia hay con respecto a los enlaces en formato `[texto](enlace)`?... (la diferencia es la aparición de `\`)
> 
> @EverVino

en el articulo 0055 hay un enlace que no se muestra apropiadamente en línea 24 
<iframe
  src="https://fast.wistia.net/embed/iframe/520zbd3tij?videoFoam=true"
  style="border: none;"></iframe>
  Es recomendable borrarlo o reemplazarlo por un .gif

2022-08-02 17:53 UTC, EverVino commented on pages/blog/0055-Rstudio/Rstudio.md
> +.. tags: ide, r, rstudio, rstudio Desktop, rstudio server, interfaz de r
poner todo en minúscula

2022-08-08 00:18 UTC, Anavelyz commented
> > Revisión de artículos: Primeros pasos con RStudio y Herramientas de visualización en R.
> > Sugerencias de palabras para el artículo 0032: R, visualización, lattice, ggplot2, tidyverse, ggmap, plotly, shiny, paquetes...
> > Sugerencias de palabras para el artículo 0055: R, RStudio, IDE, RStudio Desktop, RStudio Server, Interfaz, paquetes...
> > P. D.: Tengo una duda, algunos enlaces aparecen de la forma [texto](enlace). ¿Qué diferencia hay con respecto a los enlaces en formato `[texto](enlace)`?... (la diferencia es la aparición de `\`)
> > @EverVino
> 
> en el articulo 0055 hay un enlace que no se muestra apropiadamente en línea 24
> <iframe src="https://fast.wistia.net/embed/iframe/520zbd3tij?videoFoam=true" style="border: none;"></iframe> Es recomendable borrarlo o reemplazarlo por un .gif

2022-08-08 00:19 UTC, Anavelyz commented
@EverVino al vídeo en el artículo 0055 le añadí unos argumentos para centrarlo. ¿Sigue sin verse bien?

2022-08-08 01:13 UTC, EverVino commented
> @EverVino al vídeo en el artículo 0055 le añadí unos argumentos para centrarlo. ¿Sigue sin verse bien?

Se ve bien.

2022-08-08 01:14 UTC, EverVino approved these changes
Me parece bien. @Anavelyz. Estoy realizando el merge. Gracias.

2022-08-08 01:14 UTC, merged