Review articles 0006 and 0043
OpenScienceLabs/opensciencelabs.github.io-archive pull request #82
Opened 2022-08-16 14:31 UTC by YurelyCamacho

Review articles:

0006: ¿Qué es el lenguaje R y cómo puede ayudarte en tus proyectos?

0043: pyOpenSci: un promotor de la ciencia abierta

@EverVino

2022-08-17 01:40 UTC, EverVino requested changes
Gracias por la revisión @YurelyCamacho.
He visto que hay muchos backslashes "\\"
la barra invertida sirve de caracter de escape.
Con backslash "\\"
\[google](www.google.com)
Sin el backslash
[google](www.google.com)

2022-08-17 01:40 UTC, EverVino commented on pages/blog/0006-LenguajeR/LenguajeR.md
> +R]\(https://www.r-project.org/\). En este post daremos un paso breve sobre
Eliminar las barras invertidas "\\"
\\[Lenguaje R]\\(https://www.r-project.org/\)
=> 
\[Lenguaje R](https://www.r-project.org/)

2022-08-17 01:40 UTC, EverVino commented on pages/blog/0006-LenguajeR/LenguajeR.md
> +Gentlemann**)\[https://en.wikipedia.org/wiki/Robert_Gentleman\_(statistician)\]
Eliminar las barras invertidas "\\"

2022-08-17 01:40 UTC, EverVino commented on pages/blog/0006-LenguajeR/LenguajeR.md
> +2022 se convertirá en [Posit]\(https://posit.co/\)) que es uno de los
Eliminar las barras invertidas "\\"

2022-08-17 01:40 UTC, EverVino commented on pages/blog/0006-LenguajeR/LenguajeR.md
> +post)\[https://www.maximaformacion.es/blog-dat/para-quien-esta-pensado-r-software/\]
Eliminar los backslash "\\"

2022-08-17 01:40 UTC, EverVino commented on pages/blog/0006-LenguajeR/LenguajeR.md
> +   Language)\[https://pypl.github.io/PYPL.html\] basado en la cantidad
Eliminar los backslash "\"

2022-08-17 01:47 UTC, EverVino requested changes
Sólo cambiar la parte sugerida, Por lo demás de parece bien. gracias @YurelyCamacho

2022-08-17 01:47 UTC, EverVino commented on pages/blog/0043-PyOpenSci/PyOpenSci.md
> +en este otro enlace \[https://www.pyopensci.org/python-packages/\].
Recomendado
\[otro enlace](https://www.pyopensci.org/python-packages/)
\[repositorio GitHub](https://github.com/pyOpenSci/software-review/issues)

2022-08-17 01:47 UTC, EverVino commented on pages/blog/0043-PyOpenSci/PyOpenSci.md
> +en este otro enlace \[https://www.pyopensci.org/python-packages/\].
Eliminar los "\\"
y poner la palabra como hipervinculo

2022-08-17 02:29 UTC, YurelyCamacho commented
Ok, es que originalmente estaban sin las barras invertidas, no tengo
conocimiento de quién las colocó. Pero lo cambio y te aviso. Gracias


El mar., 16 ago. 2022 9:48 p. m., EverVino ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
>
> Sólo cambiar la parte sugerida, Por lo demás de parece bien. gracias
> @YurelyCamacho <https://github.com/YurelyCamacho>
> ------------------------------
>
> In pages/blog/0043-PyOpenSci/PyOpenSci.md
> <https://github.com/OpenScienceLabs/opensciencelabs.github.io/pull/82#discussion_r947378690>
> :
>
> > +\[https://github.com/pyOpenSci/software-review/issues\] y los aceptados
>
> +en este otro enlace \[https://www.pyopensci.org/python-packages/\].
>
>
> Recomendado
> [otro enlace](https://www.pyopensci.org/python-packages/)
> [repositorio GitHub](https://github.com/pyOpenSci/software-review/issues)
> ------------------------------
>
> In pages/blog/0043-PyOpenSci/PyOpenSci.md
> <https://github.com/OpenScienceLabs/opensciencelabs.github.io/pull/82#discussion_r947379009>
> :
>
> > +\[https://github.com/pyOpenSci/software-review/issues\] y los aceptados
>
> +en este otro enlace \[https://www.pyopensci.org/python-packages/\].
>
>
> Eliminar los "\"
> y poner la palabra como hipervinculo
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenScienceLabs/opensciencelabs.github.io/pull/82#pullrequestreview-1074945716>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWDJU2YDHG7WY3TDJHNIGDVZRAFFANCNFSM56WCKQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> <OpenScienceLabs/opensciencelabs.github.io/pull/82/review/1074945716@
> github.com>
>

2022-08-17 12:19 UTC, xmnlab commented
On Tue, Aug 16, 2022, 22:29 YurelyCamacho ***@***.***> wrote:

> Ok, es que originalmente estaban sin las barras invertidas, no tengo
> conocimiento de quién las colocó. Pero lo cambio y te aviso. Gracias


Posiblemente fue algún script o herramiebta que hemos usado ql mover de WP
a markdown, pero no fue algo intencional. Gracias por corregirlos :)

2022-08-25 01:06 UTC, EverVino approved these changes
Gracias por la revisión @YurelyCamacho 
Me parece bien, sólo he aumentado algunos tags para mejor posicionamiento en busquedas

2022-08-25 01:07 UTC, merged